# Pre-processing the data

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('weather_dataset_stage1.csv',encoding='latin-1')

In [3]:
df.head()

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,1/1/2022,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
1,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
2,2022-01-03','25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0',...,'8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
3,2022-01-04','9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0',...,'7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'
4,2022-01-05','23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0',...,'5.0','13.0','30.233','29.568','38.0','53.0','32.0','2022-01-05','01','0.6649999999999991'

In [4]:
# Checking null values

df.isnull().sum()

Date                        0
 Temperature                0
 Average humidity (%        0
 Average dewpoint (°F       0
 Average barometer (in      0
 Average windspeed (mph     0
 Average gustspeed (mph     0
 Average direction (°deg    0
 Rainfall for month (in     0
Rainfall for year (in       0
 Maximum rain per minute    0
 Maximum temperature (°F    0
 Minimum temperature (°F    0
 Maximum humidity (%        0
 Minimum humidity (%        0
 Maximum pressure           0
 Minimum pressure           0
 Maximum windspeed (mph     0
 Maximum gust speed (mph    0
 Maximum heat index (°F     0
Date1                       0
 Month                      0
 diff_pressure              0
dtype: int64

In [55]:
# Size of dataset
df.shape

(3903, 23)

##  Removal of duplicate rows and duplicate Columns

In [5]:
df=df.drop_duplicates()

In [6]:
df.shape

(3902, 23)

In [7]:
df.columns

Index(['Date', ' Temperature', ' Average humidity (%', ' Average dewpoint (°F',
       ' Average barometer (in', ' Average windspeed (mph',
       ' Average gustspeed (mph', ' Average direction (°deg',
       ' Rainfall for month (in', 'Rainfall for year (in',
       ' Maximum rain per minute', ' Maximum temperature (°F',
       ' Minimum temperature (°F', ' Maximum humidity (%',
       ' Minimum humidity (%', ' Maximum pressure', ' Minimum pressure',
       ' Maximum windspeed (mph', ' Maximum gust speed (mph',
       ' Maximum heat index (°F', 'Date1', ' Month', ' diff_pressure'],
      dtype='object')

## Fix a few labels in the given data set

In [8]:
df = df.rename(columns={' Temperature':'Avg_Temperature',
                        ' Average humidity (%': 'Avg_humidity',
                        ' Average dewpoint (°F':'Avg_dewpoint',
                        ' Average barometer (in':'Avg_barometer',
                        ' Average windspeed (mph':'Avg_windspeed',
                        ' Average gustspeed (mph':'Avg_gustspeed',
                       ' Average direction (°deg':'Avg_direction',
                       ' Rainfall for month (in' : 'Rainfall_in_a_month',
                       'Rainfall for year (in' : 'Rainfall_in_a_year',
                        ' Maximum rain per minute' : 'Max_rain_per_min',
                       ' Maximum temperature (°F' : 'Max_Temp', 
                       ' Minimum temperature (°F' : 'Min_Temp',
                       ' Maximum humidity (%' : 'Max_humidity',
                       ' Minimum humidity (%' : 'Min_humidity',
                        ' Maximum pressure' : 'Max_pressure',
                        ' Minimum pressure' : 'Min_pressure',
                       ' Maximum windspeed (mph' : 'Max_windspeed',
                       ' Maximum gust speed (mph' : 'Max_gust_speed',
                       ' Maximum heat index (°F' : 'Max_heat_index'})

In [9]:
df.columns

Index(['Date', 'Avg_Temperature', 'Avg_humidity', 'Avg_dewpoint',
       'Avg_barometer', 'Avg_windspeed', 'Avg_gustspeed', 'Avg_direction',
       'Rainfall_in_a_month', 'Rainfall_in_a_year', 'Max_rain_per_min',
       'Max_Temp', 'Min_Temp', 'Max_humidity', 'Min_humidity', 'Max_pressure',
       'Min_pressure', 'Max_windspeed', 'Max_gust_speed', 'Max_heat_index',
       'Date1', ' Month', ' diff_pressure'],
      dtype='object')

In [10]:
df=df.drop(['Date1'],axis=1)
df=df.drop([' Month'],axis=1)

In [11]:
df["Date"] = df["Date"].str.replace("'","")
df["Avg_Temperature"]=df["Avg_Temperature"].str.replace("'","")
df["Avg_humidity"] = df["Avg_humidity"].str.replace("'","")
df["Avg_dewpoint"] = df["Avg_dewpoint"].str.replace("'","")
df["Avg_barometer"] = df["Avg_barometer"].str.replace("'","")
df["Avg_windspeed"] = df["Avg_windspeed"].str.replace("'","")
df["Avg_gustspeed"] = df["Avg_gustspeed"].str.replace("'","")
df["Avg_direction"] = df["Avg_direction"].str.replace("'","")
df["Rainfall_in_a_month"] = df["Rainfall_in_a_month"].str.replace("'","")
df["Rainfall_in_a_year"] = df["Rainfall_in_a_year"].str.replace("'","")
df["Max_rain_per_min"] = df["Max_rain_per_min"].str.replace("'","")
df["Max_Temp"] = df["Max_Temp"].str.replace("'","")
df["Min_Temp"] = df["Min_Temp"].str.replace("'","")
df["Max_humidity"] = df["Max_humidity"].str.replace("'","")
df["Min_humidity"] = df["Min_humidity"].str.replace("'","")
df["Max_pressure"] = df["Max_pressure"].str.replace("'","")
df["Min_pressure"] = df["Min_pressure"].str.replace("'","")
df["Max_windspeed"] = df["Max_windspeed"].str.replace("'","")
df["Max_gust_speed"] = df["Max_gust_speed"].str.replace("'","")
df["Max_heat_index"] = df["Max_heat_index"].str.replace("'","")
df[" diff_pressure"] = df[" diff_pressure"].str.replace("'","")

In [12]:
df.columns

Index(['Date', 'Avg_Temperature', 'Avg_humidity', 'Avg_dewpoint',
       'Avg_barometer', 'Avg_windspeed', 'Avg_gustspeed', 'Avg_direction',
       'Rainfall_in_a_month', 'Rainfall_in_a_year', 'Max_rain_per_min',
       'Max_Temp', 'Min_Temp', 'Max_humidity', 'Min_humidity', 'Max_pressure',
       'Min_pressure', 'Max_windspeed', 'Max_gust_speed', 'Max_heat_index',
       ' diff_pressure'],
      dtype='object')

In [13]:
# Removal of irrelevant data
df = df[df['Date'] != '2022-02-29']

In [14]:
df['Date'] = pd.to_datetime(df['Date'])

In [15]:
df = df.reset_index(drop=True)

## Year Correction

In [48]:
target_date = '2022-01-01'
target_date = pd.to_datetime(target_date)
index = df.index[df['Date'] == target_date].tolist()
year = 2021
max_year = 2033

for i in range(index[0], df.shape[0]):
    if df.at[i,'Date'] == target_date:
        year += 1
        if year > max_year:
            break
    df.at[i,'Date'] = df.at[i,'Date'].replace(year=year)

In [50]:
df

,Date,Avg_Temperature,Avg_humidity,Avg_dewpoint,Avg_barometer,Avg_windspeed,Avg_gustspeed,Avg_direction,Rainfall_in_a_month,Rainfall_in_a_year,...,Max_Temp,Min_Temp,Max_humidity,Min_humidity,Max_pressure,Min_pressure,Max_windspeed,Max_gust_speed,Max_heat_index,diff_pressure
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,...,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,0.16600000000000037
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,...,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,0.4009999999999998
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,...,41.0,6.0,8.0,35.0,30.232,29.26,25.3,38.0,41.0,0.9719999999999978
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,...,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,0.33899999999999864
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,...,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,0.6649999999999991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,2033-07-24,64.1,62.0,49.8,29.6,3.6,5.8,240.0,0.24,4.38,...,74.9,55.3,86.0,35.0,29.686,29.577,15.0,25.3,77.4,0.10899999999999821
3896,2033-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,...,69.2,55.1,90.0,36.0,29.781,29.645,8.1,17.3,77.5,0.13599999999999923
3897,2033-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,...,71.9,50.5,90.0,40.0,29.93,29.745,11.5,15.0,77.5,0.18499999999999872
3898,2033-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,...,77.3,43.6,96.0,35.0,29.941,29.781,13.8,18.4,78.2,0.16000000000000014
3899,2033-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,...,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,0.11700000000000088;

In [65]:
df1 = df.to_csv('Cleaned_Weather_data.csv',index=False)